### IMPORT LIBRARIES

In [11]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn 
#EDA
from pathlib import Path
from ydata_profiling import ProfileReport
from IPython.display import IFrame

### LOAD DATASET

In [41]:
data_path = os.getcwd()
data_path

'/Users/marcinurbanski/Desktop/jmu_repo'

## Dataset&Columns explanation

In [70]:
exp_col = pd.read_csv('conflict_dataset_columns.csv',usecols=[0,1],index_col=[0])
exp_col

                                                            Description
Column Name
conflict_id           Unique identifier assigned to each conflict in...
location                         Country where the conflict takes place
side_a                Primary actor on side A (usually the governmen...
side_a_id               Numeric identifier for the main actor on side A
side_a_2nd                Secondary actor or supporting group on side A
side_b                              Primary opposing actor (rebel group
side_b_id               Numeric identifier for the main actor on side B
side_b_2nd                Secondary actor or supporting group on side B
incompatibility       Main issue of the conflict such as government ...
territory_name        Name of the territory if the conflict concerns...
year                  Year of the observation in which the conflict ...
intensity_level         Level of conflict intensity (1 = minor conflict
cumulative_intensity  Indicates whether the conflict has ever reache...
type_of_conflict                           Type of conflict (interstate
start_year                           Year when the conflict first began
start_date             Exact starting date of the conflict if available
ep_end                Indicates whether the conflict episode ended i...

In [79]:
data['type_of_conflict'].unique()

array([3, 2, 4, 1])

In [39]:
data = pd.read_csv('conflict_data.csv')
display(data.head())
print('-'*140)
print(data.shape)
print('-'*140)
print(data.info())

,conflict_id,location,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,territory_name,...,ep_end,ep_end_date,ep_end_prec,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,region,version
0,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2012-12-21,NaN,750,NaN,NaN,NaN,750,3,22.1
1,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2014-11-27,NaN,750,NaN,NaN,NaN,750,3,22.1
2,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1967-06-10,NaN,651,NaN,666,NaN,"651, 666",2,22.1
3,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,0,NaN,NaN,651,NaN,666,NaN,"651, 666",2,22.1
4,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1970-08-07,NaN,651,NaN,666,NaN,"651, 666",2,22.1

--------------------------------------------------------------------------------------------------------------------------------------------
(2568, 28)
--------------------------------------------------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2568 entries, 0 to 2567
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   conflict_id           2568 non-null   int64
 1   location              2568 non-null   object
 2   side_a                2568 non-null   object
 3   side_a_id             2568 non-null   object
 4   side_a_2nd            397 non-null    object
 5   side_b                2568 non-null   object
 6   side_b_id             2568 non-null   object
 7   side_b_2nd            126 non-null    object
 8   incompatibility       2568 non-null   int64
 9   territory_name        1442 non-null   object
 10  year                  2568 non-null   int64
 11  intensity_level       2568 non-null   int64
 12  cumulative_intensity  2568 non-null   int64
 13  type_of_conflict      2568 non-null   int64
 14  start_date            2568 non-null   object
 15  start_prec            2568 non-null   int64
 16  start_date2           2568 non-null   object
 17  start_prec2           2568 non-null   int64
 18  ep_end                2568 non-null   int64
 19  ep_end_date           541 non-null    object
 20  ep_end_prec           0 non-null      float64
 21  gwno_a                2568 non-null   object
 22  gwno_a_2nd            397 non-null    object
 23  gwno_b                138 non-null    object
 24  gwno_b_2nd            126 non-null    object
 25  gwno_loc              2568 non-null   object
 26  region                2568 non-null   object
 27  version               2568 non-null   float64
dtypes: float64(2), int64(9), object(17)
memory usage: 561.9+ KB
None

In [ ]:
target = [
X = [c for c in data.columns if c is not target]
y = target

In [66]:
num_cols = data.select_dtypes(include = ['int64','float64']).columns.tolist()
cat_cols = data.select_dtypes(include = ['object']).columns.tolist()

In [85]:
data[data['type_of_conflict']==1]

,conflict_id,location,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,territory_name,...,ep_end,ep_end_date,ep_end_prec,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,region,version
199,201,Cambodia (Kampuchea),Government of France,33,NaN,Khmer Issarak,160,NaN,1,Cambodia,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,22.1
200,201,Cambodia (Kampuchea),Government of France,33,NaN,Khmer Issarak,160,NaN,1,Cambodia,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,22.1
201,201,Cambodia (Kampuchea),Government of France,33,NaN,Khmer Issarak,160,NaN,1,Cambodia,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,22.1
202,201,Cambodia (Kampuchea),Government of France,33,NaN,Khmer Issarak,160,NaN,1,Cambodia,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,22.1
203,201,Cambodia (Kampuchea),Government of France,33,NaN,Khmer Issarak,160,NaN,1,Cambodia,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,22.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,285,Mozambique,Government of Portugal,36,NaN,Frelimo,428,NaN,1,Mozambique,...,1,1974-09-07,NaN,235,NaN,NaN,NaN,541,4,22.1
1172,286,South Yemen,Government of United Kingdom,28,NaN,FLOSY,265,NaN,1,Aden/South Yemen,...,0,NaN,NaN,200,NaN,NaN,NaN,680,2,22.1
1173,286,South Yemen,Government of United Kingdom,28,NaN,FLOSY,265,NaN,1,Aden/South Yemen,...,0,NaN,NaN,200,NaN,NaN,NaN,680,2,22.1
1174,286,South Yemen,Government of United Kingdom,28,NaN,FLOSY,265,NaN,1,Aden/South Yemen,...,0,NaN,NaN,200,NaN,NaN,NaN,680,2,22.1
1175,286,South Yemen,Government of United Kingdom,28,NaN,FLOSY,265,NaN,1,Aden/South Yemen,...,1,1967-11-29,NaN,200,NaN,NaN,NaN,680,2,22.1

In [68]:
X =

['location',
 'side_a',
 'side_a_id',
 'side_a_2nd',
 'side_b',
 'side_b_id',
 'side_b_2nd',
 'territory_name',
 'start_date',
 'start_date2',
 'ep_end_date',
 'gwno_a',
 'gwno_a_2nd',
 'gwno_b',
 'gwno_b_2nd',
 'gwno_loc',
 'region']